### ISSUE TITLE
api et controleur sinatra

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-blogs#11]
#### api/blogs.rb
- corriger les fautes d'orthaugraffe
- remontée d'erreur dans la route get '/exist/:sous_domaine', à faire correctement et à gérer côté IHM.

#### controller/sinatra_controller.rb
- route par défaut '/' : utiliser le Logger pour tracer l'info.
- route `get APP_PATH + '/auth/failure'`: utiliser la vue :auth_failure
- route `get APP_PATH + '/auth/:provider/callback'` :  changer ce test en positif : `redirect params[:url] if params[:url] != home`

**Comment by hquenin** [comment]
je ne comprends pas ce que tu veux dire par changer ce test en positif
cela changera quoi ?

**Comment by Pilooz** [comment]
ben ??
```
params[:url] unless params[:url] = home
```
