### ISSUE TITLE
Librairies

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-blogs#12]
#### lib/blogs
- Couper les très loooooooooongues lignes en plusieurs petites
- les méthodes `subscribe`et `unsubscribe` n'ont pas besoin d'argument
- methode `format` #198
Cette méthode affecte à rgp_id soit un id de classe soit de groupe soit un uai. Il y a confusion fonctionnelle des types de données dan cette méthode. Un uai n'est pas la même chose qu'un id de classe ou de groupe : Un id de classe ou de groupe dépend d'un uai.
Il faut renvoyer l'uai indépendamment des id classes et groupes  dans le retour de cette méthode.
```ruby
        blogs_formated.push(
          id: blog.wp_id,
          name: blog.libelle,
          type: type,
          uai: uai, # <= ce code est tout le temps renseigné
          rgptId: rgpt_id,
          owner: blog.usr_id,
          url: blog.sous_domaine,
          flux: nil,
          add: false,
          active: true
        )
```
#### lib/outils
- Ajouter un commentaire de description du module.

#### lib/wordpress
- Ajouter un commentaire de description du module.

**Comment by hquenin** [comment]
La méthode format me simplifie le coté JS, car elle me permet de renseigner le type de blogs par rapport à ce qui est renseigné dans la table blogs. 
Car si on a un blog étab dans la BDD on aura la colonne "UAI" rempli, mais pour une simplicité je préfère avoir un type (string) défini dans mes données JSON coté JS, cela est plus rapide à trier par type.
De plus fonctionnellement, je n'y peux rien si l'id d'un établissement est moins précis et unique que son "UAI". Cela reste quand même un identifiant unique qui permet de récupérer un regroupement (le nom regroupement est peut être mal choisi mais je ne vois pas de nom rassemblant les étab, classes, groupes et groupes_libres)

**Comment by Pilooz** [comment]
```
Je n'ai pas besoin d'avoir l'UAI de l'établissement pour les blog de classes, groupes, groupes_libres, car cela ne me servirait à rien donc une donnée inutile. 
```
En fait, ce qui fait qu'on va pouvoir afficher la bonne classe ou le bon groupe à un utilisateur est bien le couple UAI, Id classe ou groupe.
Un id de classe ou de groupe tout seul est bien sur identifiant mais fonctionnellement il est lié à un UAI (et même si on voulait être très rigoureux, à un millésime d'année scolaire).
