### ISSUE TITLE
Application javascript

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-blogs#14]
#### fichier constants.js
- à sortir du référentiel de code. Ignorer dans git.

#### fichier route.js 
- Les états blog.home et blog.search ont les mêmes routes sauf le `main`controller. à factoriser.
```javascript
         .state( 'blogs.home',{
            parent: 'blogs',
            url: '/',
            views: {
              'filter':{
                templateUrl:APP_PATH + '/app/views/filters/filter-home.html',
                controller: 'FilterHomeCtrl'
              },
              'aside': {
                templateUrl:APP_PATH + '/app/views/asides/aside-home.html',
                controller: 'AsideHomeCtrl'
              },
              'main': {
                templateUrl:APP_PATH + '/app/views/mains/main-home.html',
                controller: 'MainHomeCtrl'
               }
              }
            })
          .state( 'blogs.search',{
            parent: 'blogs',
            url: '/search',
            views: { 
              'filter':{
                templateUrl:APP_PATH + '/app/views/filters/filter-home.html',
                controller: 'FilterHomeCtrl'
              },           
              'aside': {
                templateUrl:APP_PATH + '/app/views/asides/aside-home.html',
                controller: 'AsideHomeCtrl'
              },
              'main': {
                templateUrl:APP_PATH + '/app/views/mains/main-search.html',
                controller: 'MainSearchCtrl'
               }
              }
            });

```

#### fichier service.js 
- Quel est donc cette méthode de sélection d'un élément dans le DOM ??
jQuery => $('#contentFilterId')
Angular => angular.element est un synonyme de $(...) de jQuery
document.getElementById est utilisé lorsque jQuery n'est pas présent.
voir => https://docs.angularjs.org/api/ng/function/angular.element
Il existe aussi une méthode jQuery `toggleClass`qui fait le travail de remove + add.

Simplifier donc cette méthode de sélection d'élément.

```javascript
    if ( filter == true ){
      angular.element(document.getElementById('contentFilterId')).removeClass("filter-none");
      angular.element(document.getElementById('contentFilterId')).addClass("filter-display");
      angular.element(document.getElementById('contentAsideId')).addClass("with-filter");
      angular.element(document.getElementById('contentMainId')).addClass("with-filter");
    } else {
      angular.element(document.getElementById('contentFilterId')).addClass("filter-none");
      angular.element(document.getElementById('contentFilterId')).removeClass("filter-display");
      angular.element(document.getElementById('contentAsideId')).removeClass("with-filter");
      angular.element(document.getElementById('contentMainId')).removeClass("with-filter");
    }

```
Même remarque pour le service `'Case'`
_D'une manière générale, le code qui touchent aux éléments du DOM devrait se trouver dans des directives plutôt que des filtres.
Une autre possibilité est de le gérer avec les `ng-class`dans les vues : 
`ng-class="{'filter-display': filter}" ...`_

#### fichier main-home.js
- Même remarque sur la sélection d'éléments.

#### fichier modal-add-blog.js
- De l'utilité du swich case dans ce code, si tous les cas sont identiques ?

```javascript
				switch($scope.currentType.code){
					case TYPES_BLOG[1].code:
					case TYPES_BLOG[2].code:
					case TYPES_BLOG[3].code:
						tempName+="-"+schoolYear();
						//on vérifie encore une fois avec le nouveau nom
						BlogsApi.exist({sous_domaine: tempName}).$promise.then(function(responseFinal){

							if (!responseFinal.exist && !Blogs.exist(tempName)) {
								$scope.subDomain = tempName;
							};
						});
				}
```
- mettre les paramètres du controleurs sur plusieurs ligne pour garder la lisibilité.

**Comment by hquenin** [comment]
Pour le constants.js, je ne comprends pas car je l'ai déjà mis dans mon .gitignore.

**Comment by hquenin** [comment]
Pour la partie du filtre, je suis obligé de faire un service, car cela se joue dans index.html qui n'a pas de controller !
En fait je dois changer les classes CSS des éléments dans un fichier html générique qui contient les différentes parties (filter, main et aside), qui eux ont chacun un controller. et c'est dans le controller main qui gère le passage en mode modification des blogs ou là, la partie filter doit disparaître.
je vais simplifier avec toogleclass mais je ne peux pas faire autrement que se soit par une directive ou un ng-class.

**Comment by hquenin** [comment]
L'utilité du switch c'est parce qu'il y 4 type de blogs et que seulement sur les trois mis dans les cases on effectue l'action.
je peux remplacer par if != type[0] si tu préfère.

**Comment by Pilooz** [comment]
Oui, simplifie moi ce switch !
