### ISSUE TITLE
Vues AngularJS

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-blogs#15]
#### index.html
- mettre les directives de mise en forme dans une css
`<growl-notification style="border-left-color: #449d44;">` avec une classe par type de notification.

#### erreur.html
Cette vue est elle utilisée ?

#### main-home.html
- `<ul style="height: 100%">` laisser à Bootstrap le soin de règler la question de la hauteur en entourant le <ul> d'un `<div class="row"><div class="col-md...." `.

- alignement du code à corriger : 
```html
<!-- Mode modification -->
<span id="main"    class="floating-button big   toggle off blanc"
	ng-click="enable_modification();"></span>
<span id="cancel"  class="floating-button small cancel     gris3 hidden"
	ng-click="cancel()"></span>
<span id="save"    class="floating-button small save       gris1 hidden"
	ng-click="save()"></span>
<span ng-hide="!modificationRight" id="action1" class="floating-button small action1    gris1 hidden"
	ng-click="add()"></span>
```

#### Main-search 
- Même remarque que sur la vue main-home.html.

**Comment by hquenin** [comment]
Pour  <ul style="height: 100%"> je le laisse comme ceci sauf que au lieu de style="height: 100%", je le met dans une classe css
le ul est aussi dans le portail et j'ai repris la même façon de faire.
