### ISSUE TITLE
Le message indiquant l'erreur est innaproprié

### ISSUE THREAD

**Issue by Pilooz** [laclasse-com/service-blogs#17]
![bug-msg-erreur](https://cloud.githubusercontent.com/assets/1265220/11630693/dd336ffc-9cfe-11e5-897f-f550413c5e97.png)
Là je mets des espaces, il devrait me dire 'interdit de mettre des espaces' ou quelque chose du genre.

**Comment by cycojesus** [comment]
« minuscule »
